#Intelligences capable of learning truth must learn first to associate perception with a model. They then must be able to test the model, prove and disprove assumptions, and revise the model until their understanding matches reality and can predict it perfectly.

class Intelligence:
    """A Class representing a person's raw intelligence, including their personality and experiences."""

    def __init__(self):
        """Initialize an instance of the Intelligence class."""
        core_attributes = {"Love-Hate":0,"Integrity-Chaos":0} #Core attributes are the core of our being, how we truly feel about and act toward things.
        #We either love or hate things (meaning we want to have those things or we want those things to cease) and we either act in accordance with our
        #knowledge and feelings or we do not.
        #More sub-attributes are needed, especially to describe physical characteristics. Also, some should be booleans, some should be ranges, and an opposite characteristic is not always necessary.
        #I will need to make a matrix of all possible perceptions. Different intelligences can perceive and then react to different things variably. Some things are imperceptible to some.
        sub_attributes = {"Charity-Greed":0,
                          "Communicativity-Silence":0,
                          "Confidence-Unconfidence"
                          "Courage-Fear":0,
                          "Creativity-Destructivity":0,
                          "Determination-Unrootedness":0,
                          "Emotion-Deadness":0,
                          "Faith-Doubt":0,
                          "Hope-Despair":0,
                          "Humility-Pride":0,
                          "Judgment-Acceptance":0,
                          "Loyalty-Treachery":0,
                          "Memory-Forgetting":0,
                          "Perception-Blindess":0,
                          "Strength-Weakness":0,
                          "Thoughtfulness-Thoughtlessness":0
                          } #Subattributes are the resultant (and more obviously apparent) personality traits springing from our core attributes 
                   #and our personal set of experiences.

        beliefs = {
            'individuals':[],
            'relationships':[],
            'resources':[],
            'morals':[]
            } #beliefs are what we think about how life really is, especially how relationships, individuals, resources, and moral laws really are.
        experiences = [] #Experiences are generated when we interact with someone or something. Experiences are raw,
                   #short-term-memory objects. They are processed through our beliefs and then have an immediate
                   # effect on both our subattributes and core attributes, depending on the criticality of the 
                   # experience to us. Ie, if we have an experience with an angel, which we had faith would one 
                   # day occur, we will necessarily treat that experience as a faith-building experience. Alternatively,
                   # if we believe that only crazy people see angels, and then we see one, we will probably start thinking
                   # we're crazy, unless otherwise convinced by some outside source.
        memories = [] #Memories are generated by experiences, but influenced by sub-attributes and beliefs, especially opinions.
                   #Example: Although we may first experience a place and consider it fantastic, if we eventually develop the
                   #belief that people from that place are cruel and we also possess the belief that people reflect their backgrounds,
                   #then we will no longer like the place.
        ideas = [] #Ideas are basically pre-goals or pre-beliefs. We determine the applicability of an idea based on our past experiences,
                   #our beliefs, and our attributes. One may have the idea to build a barn to store their crops before the winter comes,
                   #but if they believe that the crops will be stolen anyway, they will not put in the effort to build the barn.
        skills = [] # A list of named functions that define what we can do.
        goals = [] #Goals develop from ideas and define how we act in the long-term.

    def generate(self,seed="0"):
        """Generate personality attributes based on a seed value."""
        #self.personality["Humility-Pride"] = 2

    def perceive(self):
        """Perceive surroundings such as character and object locations, motion, and expressed intent."""
        #Generate a sprite group for all sprites that can presently be perceived.
        #All sprites will have state variables such as location, velocity, etc., which can be perceived based on our skills and knowledge.
        #Sprites in the group will have additional attributes added on as we interact with them. If we sense heat, the rough
        #temperature of the sprite will be recorded. If we can taste an object and we attempt to taste it, a sprite's taste will be recorded. Etc.
        #Take self's rect, do the inflate thing for all the blocks a certain distance and check collisions? Or maybe do a light thing, where a beam leaves every object from every angle, and those beams that hit the NPC are registered.
        
        

    def react():
        """React instinctively and immediately to perceptions."""
        #Add an element to every item in the 'perceived' sprite group that defines each sprite's supposed relationship to the entity.
        #This relationship can be one of the following: threat, neutrality, opportunity. For non-thinking entities, this is based only
        #on a momentum analysis and a chemical analysis (some animals chemically recognize others). For thinking-entities, this reaction
        #is also informed by memories and opinions if the entity recognizes a sprite as being the same as one in its long-term memory.
        #If a threat or opportunity is great enough, a non-thinking entity will immediately act in accordance to that, either by distancing
        #themself or approaching to fight or dominate the sprite. A thinking entity will sometimes resist even the strongest impulses
        #to act if the impulse is against their opinions/morals.

    def avoid():
        """Use any mobility functions available to distance self from threats."""        

    def fight():
        """Use any attacking capabilities to neutralize a threat."""

    def think():
        """Generate a thought based on self's personality attributes, recent experiences, etc."""
        
    def learn(self):
        """Record a memory."""
        #experience = 1
        #self.memories.append(experience)

    def desire(self):
        """Generate a desire based on personality attributes and thoughts."""
        thought = 1

    def goalset(self):
        """Generate a realistic goal based on the fact that we goalset in a way consistent to our personality, knowledge, and experiences."""
        #desire = 1
        #idea = 1
        #self.goals.append(idea)
        """
        The goal tree is going to be constructed to reflect the fact that we will only make goals that we can conceptualize, usually making
        goals that we're somewhat capable of achieving, etc.
        Factors affecting goal-setting:
        Desires-->Current knowledge set-->Morality/opinion check-->skill check+Confidence-Unconfidence check
        If we have a desire, know of a path to achieve that desire, consider the path appropriate and in-line with our opinions, and we believe
        ourself capable based on our skillset and our self-perception (or confidence), we will set a goal.
        
        Goal-seek Path
        Why (decide whether or not to goal-set for a thing, based on expected outcomes)
        What (What constitutes the desired outcome, what conversion factors are involved, etc. This is the most complex category)
        Who (who can help in achieving the goal, either willing or unwillingly, depending on goal-setter’s persona)
        Where (where is the goal most likely to be attained, pros and cons to doing it in different locations)
        When (both when is the goal applicable and when is it attainable)
        """

    def act():
        """How we will actually act. If the self is not a thinking entity, this function relies solely on perceptions and instincts. In thinking entities,
        perceptions and instincts compete with beliefs, desires, and goals."""
        
#my_intelligence = Intelligence()
#my_intelligence.learn("First Principle: Obedience")
#print(f'(Memories: {my_intelligence.memories})')